### ISSUE TITLE
Issue Assignment for Noah for BIOINF576 HW3

### ISSUE THREAD

**Issue by hojaeklee** [hojaeklee/qPCR_analysis#1]
Note: Noah is working with GSI Hojae for HW3. This issue is for Problem 2, "Working on your teammate's project". To make it easier, I have forked Noah's repo, so the teammate's project is essentially his. 

Noah can add link to this issue for Problem 2A.

Instructions for Noah:
1. Please implement `delta_ct` function. If possible, include documentation and a small test case. I found the [`qpcr` package](https://github.com/noahshanehelton/qPCR_analysis()developed by another person named Noah!) - feel free to use or call their function [DeltaCt](https://github.com/NoahHenrikKleinschmidt/qpcr/blob/main/qpcr/main/Analyser.py) in your own project. 

2. Please leave any comments in this issue for clarification.

**Comment by noahshanehelton** [comment]
Hi Hojae, 

I have worked on the deltaCt and finished most functions in the repo as well as started a tutorial: https://github.com/noahshanehelton/qPCR_analysis/blob/main/qPCR_analysis/Tutorial.ipynb

Please let me know if this looks better now/okay. I am not quite sure i understand the exact homework assignment but i believe this project is getting closer to a functional package.

**Comment by hojaeklee** [comment]
Hi Noah,

For HW3, could you please create a pull request with some implementation (a single function is fine). Also, could you assign me an issue from your repo? The goal of HW3 was for you and your teammate to work on each other's repo, create pull requests with implementation, and review the code.

**Comment by noahshanehelton** [comment]
Got it, just updated some functions. Will assign an issue to you now.

**Comment by hojaeklee** [comment]
Hi @noahshanehelton, please create a pull request with your work to this repo for HW3, Problem 2
